#!/usr/bin/env bash
set -eux

mamba env update --file mamba.yml --prefix ${NB_PYTHON_PREFIX}

python -m pidgy kernel install
# TODO: get working
# python -m calysto_hy install

pushd ft
  pushd jupyterlab-lsp
    python -m pip install -e .
  popd

  pushd wxyz
    doit setup_py_dev
  popd
popd

jupyter serverextension enable --sys-prefix --py jupyter_videochat

if [ ! -d _lab ]; then
  bash labBuild
fi

rm -rf ${NB_PYTHON_PREFIX}/share/jupyter/lab/{settings,static,extensions}
cp -r _lab/* ${NB_PYTHON_PREFIX}/share/jupyter/lab

pushd ft/jupyterlab-drawio/drawio-export
  jlpm --ignore-optional || jlpm || echo "well, let's try anyway"
popd

mkdir -p ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings
cp overrides.json ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings

jupyter labextension disable @jupyterlab/extensionmanager-extension

jupyter serverextension list
jupyter kernelspec list
jupyter labextension list

conda clean -yaf
jlpm cache clean
